/**
 * Length of the base64url-encoded session token generated by generateState().
 * generateState() encodes 32 random bytes -> 43 base64url characters (no padding).
 */
export const SESSION_TOKEN_LENGTH = 43;
